### PR TITLE
Draft: Using ESBuild instead of create react app

### PR DESCRIPTION
**Pull request by wegry**
# Rendering the default front end with ESBuild built js in 214ms

## Handling embedded files and CLI flags

I might be misremembering the "baked in front end" aspect of the DSK, but I believe the default front end is baked in for the development AND prod dsk binaries? Or do we only bake the default front end in when there isn't a custom one specified?

What should the CLI DX look like for custom playground components? Do we want a separate set of flags to load in that path? I suspect the answer is probably yes. Which CLI code path would this ESBuild version of the code apply to?

- [ X ] Built in front end
- [ X ] Built in front end with custom playground components
- [  ] Custom front end

Does this match your expectations?

## Other hiccups

There were a couple other hiccups that I sort of hedged my way through.

1. Yarn 2's PnP [is compatible with ESBuild](https://github.com/yarnpkg/berry/tree/master/packages/esbuild-plugin-pnp), but _only_ if we call ESBuild with `yarn`.  Instead of calling `yarn` from the dsk itself, I swapped `yarn`'s module resolution to use node_modules once more.
2. ESBuild can't natively handle HTML entry points yet. Inlined HTML is doing the trick for now, but it might not be as robust as we want it to be.
3. Extricating the project from Create React App has some lingering effects. Jest configuration seems broken, ESLint might be busted too. I'll try patching that up some time this week if I can.
4. All make targets might not work due to the above issue. I'm hoping CI will catch a decent chunk.

### CODE REVIEW

**Review by mariuswilms — COMMENTED** [review]
There's also a way to use esbuild without ejecting, although this still uses webpack as the coordinator and esbuild just as a kind of backend. Using [craco](https://github.com/gsoft-inc/craco) this can be configured like this:

```
const esbuild = require('craco-esbuild');

module.exports = {
  plugins: [{ plugin: esbuild }],
};
```

Having a pure esbuild build would also be attractive, but only if we can get rid of most the ejected code and webpack. 

I'm in favor of the first as it'd makes updates easier and fast_er_.

Or do you think we don't need most of what CRA provides and getting rid of that makes updates easy and it's worth the effort?

**Comment by mariuswilms** [comment]
I've remembered that I used `@yarnpkg/esbuild-plugin-pnp` with esbuild to support yarn's PNP mode.

**Comment by wegry** [comment]
About https://github.com/rundsk/dsk/pull/140#pullrequestreview-659918374, I think we probably _have_ to drop CRA in its entirety to be able to achieve builds of individual playgrounds. Having two build invocation approaches (using yarn ahead of time with make) and ESBuild in Go for playgrounds is something I hope to avoid.

Removing webpack itself isn't too hard (it's not necessary in this current incarnation even). I was trying to get the ejected version of just to run as well, but it's crashing on non-es5 code in a dependency at the moment.

I'm going to circle back and clean out webpack, probably just leaving jest and esbuild in working order.

*edit:* After a little fiddling, jest is back up and running. I think the only bit @ChristophLabacher'll miss if this change makes it in is how to run a local dev server for things like hot reloading. Otherwise, jest/building should function (hopefully as expected).

**Comment by mariuswilms** [comment]
In the earlier stage of one of our software design ideas we've assumed it'll be required that we bundle frontend and (user provided) playground code together. Taking this assumption it'd be justified to have the bundling process for both frontend and playground code in Go exclusively. I wouldn't want to call  `make` or `yarn` from Go code in that case either.

But this changed with the design progressing: We've figured that user provided code will only ever live inside playgrounds. We didn't have this clear separation in the beginning. Now that we have we can see that we "only" need to bundle the playground code by itself. 

There is no urgency to use a different build process. Using more standard techniques here will make it easier for possible contributors to understand and begin to contribute as well as for people to use it as an example to build their own custom frontend.

This leads me to the following conclusions and a suggestion to give this PR a good goal/scope:

We should not use a custom build process for our frontend but use a standard JavaScript (esbuild powered) build chain. 

- Consequently we should drop the changes to `frontend/main.go`. But we can use them in the implementation of the HTTP handler for runtime bundling playground code, so they are not lost. We should use that snippet and build upon it for creating the playground iframe's HTML.
- We build the frontend through make + yarn + PnP. It's okay to call esbuild through yarn so PnP will work. PnP is preferred because of its performance but not a requirement though.
- We keep using esbuild as the frontend bundler but installed via package.json/npm/yarn and controlled via an i.e. `esbuild.js` build script.

We should now use this PR and your work that already happpened here to get rid of CRA and webpack, so we can build the frontend with just esbuild. We must however ensure that certain tooling we kind of still works like it did before. Using esbuild insteed of CRA will make the frontend more future proof and with less dependencies easier to upgrade and to understand.

- [x] We need to be able to run existing tests with `make test` (inside `frontend`)
- [ ] We need to be able to build the bundle with `make build` (inside `frontend`)
  - [ ] The PR will need to change the build process so it again uses the icons and HTML skeleton 
- [ ] We need to be able to start a development server with `make dev`, 
  - hot reloading is nice but not a requirement
  - any development server can be used
- [ ] We need to be able to lint using `make lint`

**Comment by mariuswilms** [comment]
> There's also a way to use esbuild without ejecting, although this still uses webpack as the coordinator and esbuild just as a kind of backend. Using craco this can be configured like this:

Using esbuild with webpack is not the way to go, when we can build the whole app with esbuild alone already(?). 

> Yarn 2's PnP is compatible with ESBuild, but only if we call ESBuild with yarn. Instead of calling yarn from the dsk itself, I swapped yarn's module resolution to use node_modules once more.

We should build through yarn and are than able to use PnP.

> ESBuild can't natively handle HTML entry points yet. Inlined HTML is doing the trick for now, but it might not be as robust as we want it to be.

That's tricky and I don't know of a good soliution off the top of my head. But I'm sure one exists. Doesn't webpack use a library that can be used on its own?

> Extricating the project from Create React App has some lingering effects. Jest configuration seems broken, ESLint might be busted too. I'll try patching that up some time this week if I can.

Great!

> All make targets might not work due to the above issue. I'm hoping CI will catch a decent chunk.

I can help you with that, just pull me in when I should fix these.

> I might be misremembering the "baked in front end" aspect of the DSK, but I believe the default front end is baked in for the development AND prod dsk binaries? Or do we only bake the default front end in when there isn't a custom one specified?

In development we start by switching into the frontend directory and start a development server + watch build in there as with regular other JavaScript apps. There's nothing special there. The backend will not serve the frontend code in development.

In production we always bake in, the prod Go build expects a prebuild app to bake in inside `frontend/build`. But you can provide an alterntive path during build time via `FRONTEND`.

> What should the CLI DX look like for custom playground components? Do we want a separate set of flags to load in that path? I suspect the answer is probably yes. Which CLI code path would this ESBuild version of the code apply to?

I'm not sure how relevant these questions are, I think we've answered them in our discussions around the design doc.

**Comment by wegry** [comment]
> Consequently we should drop the changes to frontend/main.go. But we can use them in the implementation of the HTTP handler for runtime bundling playground code, so they are not lost. We should use that snippet and build upon it for creating the playground iframe's HTML.

I agree that this PR as it exists is probably more useful as an exploratory exercise not intended to be merged.

About PnP, I agree on the points about performance. I think something like the following [Mermaid generated chart](https://mermaid-js.github.io/mermaid-live-editor/edit/#eyJjb2RlIjoiZ3JhcGggVERcbiAgICBzdWJncmFwaCBpZGUxIFtCdWlsZCBFbnRyaWVzXVxuICAgIEFbRFNLIEZyb250ZW5kXVxuICAgIEJbUGxheWdyb3VuZHNdXG4gICAgZW5kXG4gICAgc3ViZ3JhcGggaWRlMiBbVW5jaGFuZ2VkXVxuICAgIENbTWFrZV1cbiAgICBHW0NyZWF0ZSBSZWFjdCBBcHBdXG4gICAgRFtZYXJuIFBuUF1cbiAgICBKW0J1aWx0IGluIGZyb250IGVuZF1cbiAgICBlbmRcbiAgICAlJSBUaGlzIHdvdWxkIHByZXN1bWFibHkgYmUgcmVhY3QtZG9tL3JlYWN0LlxuICAgIEVbWWFybiBVbnBsdWdnZWRdXG4gICAgRltHbyBFU0J1aWxkIEFQSV1cbiAgICBIW3JlYWN0L3JlYWN0LWRvbS9wbGF5Z3JvdW5kLXJ1bnRpbWVdXG4gICAgSVtQbGF5Z3JvdW5kIFNvdXJjZV1cblxuXG4gICAgQSAtLT4gQ1xuICAgIEMgLS0-IEdcbiAgICBHIC0tPiBEXG4gICAgRyAtLT4gSlxuICAgIEcgLi0-IEVcbiAgICBCIC4tPiBGXG4gICAgRiAuLT4gRVxuICAgIEggLS4tIEVcbiAgICBJIC0uLSBGXG4iLCJtZXJtYWlkIjoie1xuICBcInRoZW1lXCI6IFwiZGVmYXVsdFwiXG59IiwidXBkYXRlRWRpdG9yIjpmYWxzZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOmZhbHNlfQ) would work for the playground build without touching the existent make + yarn + PnP bits. 

mermaid-diagram-20210610185349

We would selectively `yarn unplug` bits of the third party modules to minimize the hit from [the node_modules problem](https://yarnpkg.com/features/pnp#the-node_modules-problem). 

I do think we want to use the go ESBuild API for Playground builds, unless you're thinking @mariuswilms that we call make from Go?

**Pull request closed without merging**
